<?php

$static_routes = [
    # every route path should end with a slash
    null                    => ['controller' => 'NotFoundController',
                                'action'     => 'notFoundAction',
                                'params'     => [/*empty*/]],
    '/'                     => ['controller' => 'IndexController',
                                'action'     => 'indexPageAction',
                                'params'     => [/*empty*/]],
    '/login/'               => ['controller' => 'LoginController',
                                'action'     => 'loginPageAction',
                                'params'     => [/*empty*/]],
    '/login/auth/'          => ['controller' => 'LoginController',
                                'action'     => 'loginAuthAction',
                                'params'     => ['username', 'password']],
    '/logout/'              => ['controller' => 'LoginController',
                                'action'     => 'logoutAction',
                                'params'     => [/*empty*/]],
    '/register/'            => ['controller' => 'LoginController',
                                'action'     => 'registerAction',
                                'params'     => ['username', 'password', 'email']],
    '/user/'                => ['controller' => 'UserController',
                                'action'     => 'userPageAction',
                                'params'     => [/*empty*/]],
    '/user/edit/'           => ['controller' => 'UserController',
                                'action'     => 'userEditAction',
                                'params'     => [/*empty*/]],
    '/user/save/'           => ['controller' => 'UserController',
                                'action'     => 'userSaveAction',
                                'params'     => ['username', 'email', 'birth_date', 'first_name', 'last_name', 'gender']],
    '/user/resetpassword/'  => ['controller' => 'UserController',
                                'action'     => 'resetPasswordAction',
                                'params'     => ['password', 'confirm_password']],
];
